Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms

- Data Structures/Trie/Trie.py
Added Trie Data structure code in python
> python code for Trie Datastructure issue #1

- Data Structures/Queue/queue.cpp
This is the implementation of queue using the array.
> Added the queue implementation using array

- Algorithms/Longest Increasing Subsequence.cpp
C++ Program for finding the Longest Increasing Subsequence in an array.
> Added Longest Increasing Subsequence

- Data Structures/Stack/StackUsingArray.java
Stack Implementation Using Array
> Added Stack Implementation using Array in Java

- Data Structures/Stack/StackUsingLinkedList.java
Stack Implementation Using Linked List
> Added Stack Implementation Using Linked List in Java

- Data Structures/Queue/QueueUsingArray.java
Queue implementation using Array in Java
> Queue using Array

- Data Structures/Strings/Anagram.py
- Data Structures/Strings/Palindrome.py
- Data Structures/Strings/ReverseEachWord.py
- Data Structures/Strings/ReverseString.py
- Data Structures/Strings/VowelsConsantsCount.py
Added anagram,  Palindrome, Reverse each word in a string, reversing a word, Counting the number of vowels and constants in a string.
> Added to DS-->String

- Data Structures/Stack/Maximumproductofindexes.py
Stack: Maximum product of indexes of next greater on left and right.
> Maximum product of indexes of next greater on left and right

- Algorithms/the-knights-tour-problem-backtracking.py
I have added knights tour problem using backtracking in algorithm folder. Please review it @Anishukla
> added the knights tour problem using backtracking in .py file

- Data Structures/Stack/Stack_Peek.py
- Data Structures/Stack/Stack_Pop.py
- Data Structures/Stack/Stack_Push.py
Please approve. Would help me a lot in Hacktoberfest :)
> Added Functions for stack in Python

- Algorithms/COVID Assistant.py
Python Script to fetch data from mohfw.gov.in regarding COVID statistics. Also displays data state-wise.
> Create COVID Assistant.py

- .vscode/settings.json
- Data Structures/Queue/queue.py
- Data Structures/Stack/stack.py
Tha latest commit is the perfect one please consider that without "&" one. Contributing @Hacktoberfest 2020.
> Stack & Queue Implementation using python 

- Algorithms/flatten.py
Given an array that may contain nested arrays,
produce a single resultant array.
> Implement Flatten Arrays.

- Algorithms/countingsort.py
> countingsort.py

- Data Structures/Stack/Stack.c
Implemented stack using linked list in C
> add stack using linked list

- Data Structures/Recursion/SumOfNaturalNoTailTypeRecursion.c
- Data Structures/Recursion/TaylorSeries.c
- Data Structures/Recursion/nCr.c
@Anishukla Happy to Contribute! Added my first PR 👍🏻
> Added Recursion Problems

- Algorithms/binarySearch.java
added binary search in algoithms
> added binary search

- Data Structures/Queue/Queue.py
Please merge my pull request @Anishukla
> Added the code for Implementing a Queue using Python

- Algorithms/Rat_in_a_maze.py
I have added Rat in  a maze algorithm using backtracking in algorithm folder. @Anishukla Please review it
> added Rat in a maze backtracking algorithm in python file

- Data Structures/FenwickTree/fenwickTree.cpp
An interesting data structure called the Fenwick tree to add to this collection
> Added Fenwick Tree

- Data Structures/Segment Tree/README.md
- Data Structures/Segment Tree/SegmentTreeNaive.cpp
- Data Structures/Segment Tree/SegmentTreeOptimal.cpp
Segment Tree naive implementation with point update and range queries in O(logn) time. Memory inefficient implementation.
> Segment Tree Naive Implementation

- Algorithms/N_queen_problem.py
- Algorithms/hamiltonian_cycle_backtracking.py
I have added N queen problem solved using backtracking in .py file in algorithm folder. @Anishukla please review it
> added N queen problem using backtracking

- Algorithms/m_coloring_problem_backtracking.py
I have added M coloring problem using backtracking in .py file in algorithm folder. @Anishukla please review it
> added M coloring problem using backtracking

- Data Structures/Queue/Queue.py
- Data Structures/Searching and Sorting/countSort.cpp
- Data Structures/Stack/infixToPostfix.cpp
created Count Sort for datastructure/Searching and Sorting
> created CountSort

- Data Structures/Disjoint Set/Disjoint Set Union.cpp
- Data Structures/Disjoint Set/README.md
- Data Structures/Heap/MaxHeap.cpp
- Data Structures/Heap/MinHeap.cpp
- Data Structures/Heap/README.md
Disjoint Set Union Data Structure for problems based on union find and connected components of graph.
> Disjoint Set 

- Algorithms/BinarySearch.py
- Algorithms/Fibonacci.py
Two Fibonacci implementations using recursive functions, one have an exponential time complexity and the second has a linear complexity.
> Fibonacci implementation in Python

- Data Structures/AVL Tree/avl_tree.py
- Leetcode/Python/Merge_k_sorted_lists.py
- Leetcode/Python/ZigZag_Conversion.py
Programs in Leetcode/Python:
- ZigZag Conversion
- Merge k Sorted List
Programs in Data Structure/AVL Tree:
- Insertion and Deletion of AVL Tree (along with Preorder and Inorder traversal.)
> added Leetcode/Python, "Data Structures/AVL Tree"

- Leetcode/CPP/46. Permutations.cpp
I have added the solution to " problem_number 46 : Permutations " on LeetCode. It is implemented in C++. Let me know if something has to be changed.
> Added Permutations.cpp (Problem number 46) on LeetCode

- Algorithms/C++/logTimeExponentiation.cpp
> Implement logarithmic-time exponentiation algorithm.

- Algorithms/C++/Kosaraju Algorithm.cpp
- Algorithms/C++/LCA in O(n) and O(logN).cpp
- Algorithms/C++/Rabin Karp.cpp
I have added my implementations of Kosaraju Algorithm which is used to find the Strongly Connected Components in a Graph, an algorithm to find Lowest Common Ancestor(LCA) of 2 nodes in a tree in O(n) and O(logN) time complexities and Rabin Karp Algorithm which is a pattern searching algorithm with an average time complexity of O(n + m).
> Added Kosaraju algorithm, LCA and Rabin Karp algorithm

- HackerRank-30-Days-Of-Code/Python/0.py
- HackerRank-30-Days-Of-Code/Python/1.py
- HackerRank-30-Days-Of-Code/Python/10.py
- HackerRank-30-Days-Of-Code/Python/11.py
- HackerRank-30-Days-Of-Code/Python/12.py
- HackerRank-30-Days-Of-Code/Python/13.py
- HackerRank-30-Days-Of-Code/Python/14.py
- HackerRank-30-Days-Of-Code/Python/15.py
- HackerRank-30-Days-Of-Code/Python/16.py
- HackerRank-30-Days-Of-Code/Python/17.py
- HackerRank-30-Days-Of-Code/Python/18.py
- HackerRank-30-Days-Of-Code/Python/19.py
- HackerRank-30-Days-Of-Code/Python/2.py
- HackerRank-30-Days-Of-Code/Python/20.py
- HackerRank-30-Days-Of-Code/Python/21.cpp
- HackerRank-30-Days-Of-Code/Python/22.py
- HackerRank-30-Days-Of-Code/Python/23.py
- HackerRank-30-Days-Of-Code/Python/24.py
- HackerRank-30-Days-Of-Code/Python/25.py
- HackerRank-30-Days-Of-Code/Python/26.py
- HackerRank-30-Days-Of-Code/Python/27.py
- HackerRank-30-Days-Of-Code/Python/28.py
- HackerRank-30-Days-Of-Code/Python/29.py
- HackerRank-30-Days-Of-Code/Python/3.py
- HackerRank-30-Days-Of-Code/Python/4.py
- HackerRank-30-Days-Of-Code/Python/5.py
- HackerRank-30-Days-Of-Code/Python/6.py
- HackerRank-30-Days-Of-Code/Python/7.py
- HackerRank-30-Days-Of-Code/Python/8.py
- HackerRank-30-Days-Of-Code/Python/9.py
Added my solution to 30-days-of-code in Python3
By Mansi Modi
> Hackerank-30days-of-code-python3 solutions

- Data Structures/Graph/Dijkstra.cpp
> Added C++ implementation of Dijkstra's shortest path algorithm.

- Data Structures/Graph/Prim.cpp
> Add C++ implementation of Prim's Minimum Spanning Tree algorithm.

- Leetcode/CPP/54. SpiralMatrix.cpp
Please let me know if any changes are required.
> Added ProblemNumber:54 SpiralMatrix.cpp to Leetcode/CPP

- Leetcode/CPP/129. Sum Root to Leaf Numbers.cpp
Added leetcode question 129. Sum Root to Leaf Numbers with solution
> Added a leetcode question with cpp solution

- Data Structures/Graph/FloydWarshall.cpp
> Add C++ implementation of Floyd-Warshall shortest path algorithm.

- Data Structures/Stack/TowerOfHanoi.cpp
I have added Tower of Hanoi an application of Stack using C++.
> Added Tower of Hanoi-Stack

- Data Structures/Segment Tree/SegTreeUsingModule.py
In this .py file, I used the Segment-Tree library. This module helps to avoid the implementation of segmentation tree. It generally reduces the stress of implementing the Segment tree .
> Segment Tree implementation using python

- Data Structures/Tree/TreeTraversal.py
Code for Preorder, Inorder and PostOrder Traversal.
> Added python implementation of tree traversal

- Leetcode/CPP/42. Trapping Rain Water.cpp
Adding solution to leetcode problem trapping rain water in C++
> 42. Trapping Rain Water

- Leetcode/Python/two-sum.py
> two-sum.py

- Algorithms/C++/Permutation.cpp
> Adding permutation

- Data Structures/Recursion/No_of_island.cpp
> Added new code

- Algorithms/C++/exponential_search.cpp
- Algorithms/C++/interpolation_search.cpp
- Algorithms/C++/jump_search.cpp
1.Jump-Search algorithm is searching algorithm for sorted array.
Its check fewer element by jumping by fixed number.
2.Exponential Search algorithm is searching algorithm as well.
size of search increase by power of 2 eg-2^0,2^1 etc and if , no element found till last element search size will start
reducing backward.
3. Interpolation Search is an algorithm for searching for a key in an array that has been ordered by numerical values assigned to the keys.
> Jump-Search,Exponential Search,Interpolation Search

- Algorithms/kruskal.py
to run this code you need to create a graph
grp = Graph(4) 
and add the edges to it
grp .addEdge(0, 1, 10) 
grp.addEdge(0, 2, 6) 
grp.addEdge(0, 3, 5) 
grp.addEdge(1, 3, 15) 
grp.addEdge(2, 3, 4) 
then run the method
g.KruskalMST()
> kruskal algorithm

- Leetcode/CPP/45. Jump Game II.cpp
Solution to Jump game II in C++
> 45. Jump Game II.cpp

- Data Structures/Recursion/Factorial_Recursive.py
> Recursive Factorial

- Algorithms/Java/Kandane.java
- Algorithms/Java/RotateArray.java
- Algorithms/Java/countingSort.java
- Algorithms/Java/quickSort.java
> Algorithms

- Algorithms/C++/LIS(NlogN).cpp
Longest Increasing Subsequence in O(NlogN)
> LIS(NlogN).cpp

- Data Structures/LinkedList/ReverseLinkedList.cpp
Reverse a Linked List (given a pointer to the head node)
> ReverseLinkedList.cpp

- Data Structures/Graph/Bellman_ford.cpp
Implementation of Bellman Ford algorithm
> -a cpp bellman ford algorithm

- Data Structures/LinkedList/delete_display_circular_linked_list.c
This code will insert first in all element from the user and after inserting it will display and delete all the elements one by one.
> Insert Delete and Display Function in Linked List

- Leetcode/CPP/1143. Longest Common Subsequence.cpp
Added dp solution for longest common subsequence of two strings.
> Create 1143. Longest Common Subsequence.cpp

- Algorithms/Javascript/Mode-Median-Mean.js
add mean mode median in javascript
> add mean mode median in javascript

- Algorithms/C++/HourGlass problem.c
Added HourClass Problem in C++
> Added HourGlass Problem

- Algorithms/Java/BacktrackingMaximumSizeSubset.java
> Added BacktrackingMaximumSizeSubset .java

- Data Structures/LinkedList/Create Linked List Cycle.java
Create Create Linked List Cycle in Java
> Create Create Linked List Cycle in Java

- Algorithms/C++/Kahn’s algorithm for Topological Sorting.cpp
> Create Kahn’s algorithm for Topological Sorting.cpp

- Algorithms/Java/SelectionSort.java
- Leetcode/Java/1095.Find in Mountain Array.java
The following code contains the solution of Leetcode problem 1095. Find in Mountain Array in Java
> Solved Leetcode problem 1095. Find in Mountain Array (java)

- Algorithms/C++/Conversion_from_Binary_to_Decimal.cpp
@Anishukla Please merge my PR under Hacktoberfest'21
> Added code for conversion of Binary number into decimal form

- Algorithms/C++/Max_Sum_Inc_Subs.cpp
> dp: Maximum Sum Inc Subseq

- Data Structures/AVL Tree/avl_tree.java
Contributing to Hacktoberfest 2021
Added a new algorithm AVL tree in java language
> Added a new algorithm avl tree in java language

- Algorithms/C++/merge_sort.cpp
Implementation of merge sort #hacktoberfest2021
> Contributed by Srijan Singh Hacktoberfest 2021

- Algorithms/C++/Staicase_Search.cpp
Satircase Search algorithm is used to search element in a 2D matrix. If we use linear search algorithm then the time complexity will be O(N*N) but the time complexity of staicase search algorithm will be O(N). The only condition is that
staircase search algorithm is only applied on the sorted 2D array means both rows and columns of the 2D array will be sorted.
> Staircase Search Algorithm

- Algorithms/Javascript/Fisher-Yates-Shuffle.js
I added the **Fisher-Yates** algorithm to mix an array in JavaScript
@Anishukla Can you add the `hacktoberfest-accepted` label, if is okay for you?
> Feat: Fisher Yates Shuffle

- Data Structures/LinkedList/element_deletion_from_begining_singly_linked_list.c
Step 1: IF HEAD = NULL
Write UNDERFLOW
Go to Step 5
[END OF IF]
Step 2: SET PTR = HEAD
Step 3: SET HEAD = HEAD -> NEXT
Step 4: FREE PTR
Step 5: EXIT
> Element Deletion from beginning element of singly linked list

- Algorithms/Java/CyclicSort.java
Use this algorithm when you need to sort an array having continuous number, i.e. [1, n]. 
Worst Case scenario -> O(n).
> Adding Cyclic Sort algorithm in the repository

- Algorithms/C++/Kadanes Algorithm.cpp
Kadane's Algorithm is used to find the maximum subarray sum in O(N) time complexity. Usually time complexity of finding maximum array sum is O(N^3).
> Kadane's Algorithm

- Leetcode/CPP/206. Reverse Linked List.cpp
I have added a solution to leetcode problem in C++ language.
The question link is mentioned as a comment inside the code.
> 206. Reverse Linked List added

- Data Structures/LinkedList/SplitLinkedList.cpp
**Added split linked list in parts to Data Structure section**
**Checks**
> Added split linked list in parts

- Leetcode/CPP/48.RotateImage.cpp
This is a PR for issue #154. Rotate Image is a medium level problem on leetcode.
> Added 48. Rotate Image to Leetcode CPP

- Leetcode/CPP/4. Median of Two Sorted Arrays.cpp
**Added leetcode median of sorted array problem in CPP section**
**Checks**
> Added leetcode median of sorted array problem

- Leetcode/JavaScript/rotate-array/README.md
- Leetcode/JavaScript/rotate-array/index.js
- Leetcode/JavaScript/rotate-array/index.spec.js
I solved the problem [#189](https://leetcode.com/problems/rotate-array) (from LeetCode) in JavaScript (tests included)
@Anishukla If that's good for you, can you add the `hacktoberfest-accepted` label, and close the related issue [#190](https://github.com/Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms/issues/190) ? 🙏
> Feat: Rotate Array Solution

- Data Structures/Stack/Prefix_Expression_Evaluation.cpp
@Anishukla Please merge my PR under Hacktoberfest'21
> Added Code for Prefix Expression Evaluation

- Leetcode/CPP/37. Sudoku Solver.cpp
**Added leetcode problem sudoku solver using backtracking approach in CPP section**
**Checks**
> Added sudoku solver problem

- Leetcode/Python/NonOverlappingIntervals.py
Added LeetCode Non Overlapping Intervals problem #435 in Leetcode/python folder
Checks
> Added Non overlapping intervals problem in Leetcode folder

- Leetcode/CPP/18. 4Sum.cpp
- Leetcode/CPP/28. Implement strStr().cpp
> Added leetcode 4Sum

- Leetcode/CPP/28. Implement strStr().cpp
Added **Leetcode 28. Implement strStr()**
Checks
> added leetcode-28

- Algorithms/Clang/BinarySearchRecursive.c
- Algorithms/Clang/HeapSort.c
- Algorithms/Clang/InsertionSort.c
- Algorithms/Clang/LinearSearch.c
- Algorithms/Clang/MergeSort.c
- Algorithms/Clang/RadixSort.c
Added C Language Algorithms:
- BinarySearchRecursion.c
- BubbleSort.c
- HeapSort.c
- InsertionSort.c
- LinearSearch.c
- MergeSort.c
- RadixSort.c
> Clang Algorithms

- Leetcode/CPP/intersection_of_array.cpp
I have added the intersection of two arrays cpp program where it displays  the common elements of the two arrays.
> Leetcode: Intersection of two arrays

- Leetcode/CPP/75.SortColors.cpp
This is a PR for issue #154. Sort Colors is a medium level problem on leetcode.
> Added 75. Sort Colors to Leetcode CPP

- Leetcode/Python/position_for_service_centre.py
> Leetcode: 1515. Best Position for a Service Centre

- Leetcode/CPP/51. N-Queens.cpp
This is hard level question from leetcode.
> 51.N-Queens

- Leetcode/Java/410. Split Array Largest Sum.java
This file contains the solution of Leetcode Problem 410. Split Array Largest Sum
> Solving Leetcode Problem 410. Split Array Largest Sum

- Leetcode/Java/56.Merge Intervals.java
Hi,
I've added my solution for the Leetcode _Medium_ problem 56, _Merge Intervals_. 
My PR is for the contributions mentioned in #154.
Link to the problem: https://leetcode.com/problems/merge-intervals/
I've also mentioned the time and space complexity of my solution.
It was really fun solving this problem. Working on solving more problems and contributing their solutions to the repository.
Please do let me know if there are any changes needed, in my pull request.
Thanks.
> Added Java Solution for Leetcode Problem 56. Merge Intervals

- Data Structures/Searching and Sorting/CountSort.java
- Data Structures/Searching and Sorting/QuickSort.java
I have added two Data Structure & Algorithm Program i.e. Count Sort and Quick Sort inside Searching and Sorting Folder
> Added CountSort and QuickSort in java language.

- Leetcode/CPP/707._Design_Linked_List.cpp
<a href="https://leetcode.com/problems/design-linked-list/">Problem Link</a>
Added the solution of the above problem
> Adding Solution of Leetcode Problem Number 707

- Data Structures/Searching and Sorting/binarySearchRecur.py
#Binary search Recursive in python
#Code is to find any element in array.
> create BinarySearch in py

- Algorithms/C++/Dutch_national_flag_algorithm.cpp
added one of the important algorithm for coding interviews.
For DNF (Dutch National Flag), we sort an array of 0, 1, and 2's in linear time that does not consume any extra space. We have to keep in mind that this algorithm can be implemented only on an array that has three unique elements.
> added Dutch national flag algorithm

- Algorithms/Javascript/fibonacci.js
@Anishukla I made this PR for adding fibonacci in javascript. Please review. Thanks!
> add fibonacci in Javascript

- Data Structures/Treap/treap.cpp
- Data Structures/Treap/treap_implicit.cpp
Added implementations for Treap and Implicit Treap
> Added Treap in DS

- Data Structures/Stack/Max-Area-Under_Histogram.cpp
https://www.geeksforgeeks.org/largest-rectangle-under-histogram/
> Max Area Under Histogram Using Stack

- Leetcode/Python/SumOfBeautyInArray.py
2012. Sum of Beauty in the Array
Problem Link: https://leetcode.com/problems/sum-of-beauty-in-the-array/
> Leetcode #2012: Medium – Sum of Beauty in Array

- Leetcode/CPP/96. Unique Binary Search Trees.cpp
Added leetcode Unique Binary Search Trees
Checks
> Added leetcode Unique Binary Search Trees

- Data Structures/Stack/InfixToPostfix.cpp
Dear Sir,
I have added Infix To Postfix in C++ using stack. 
Thanking You,
Shlok Jhunjhunwala.
> Added InfixToPostfix.cpp

- Leetcode/CPP/49. Group Anagrams.cpp
Added leetcode Group Anagram
Checks
> Added leetcode group-anagram

- Data Structures/Stack/infixToPostfix.cpp
- Leetcode/CPP/138. Copy List with Random Pointer.cpp
**Added leetcode problem copy list with random pointer in CPP section**
**Checks**
> Added copy list with random pointer

- Algorithms/C++/mergeKSortedArrays.cpp
Kindly merge this PR . The code merges K sorted arrays using min heap.
> Merge K sorted arrays in C++ using heap

- Leetcode/Java/18.Maximum_Length_of_Repeated_Subarray.java
Issue: #298 
Problem : Leetcode - https://leetcode.com/problems/maximum-length-of-repeated-subarray/
718. Maximum Length of Repeated Subarray
Language- Java
> LeetCode:  718. Maximum Length of Repeated Subarray

- Leetcode/CPP/20. Valid Parentheses.cpp
**Added leetcode 20. Valid Parentheses.cpp**
**Checks**
> Added leetcode 20. Valid Parentheses.cpp

- Leetcode/CPP/146. LRU Cache.cpp
**Added cpp solution to leetcode LRU_Cache**
Checks
> Added C++ solution to 146. LRU Cache

- HackerRank/Python/No_Idea.py
> Python HackerRank Solution : Problem [No Idea!]

- Data Structures/Strings/Zalgo.cpp
C++ code for Z algorithm which searches for a pattern in a text string.
> Add Z-Algorithm in String DS
